"""
Generates firmware/include/generated_pos_config.hpp: real triangulated LED
positions baked in as compile-time constants, so a clean flash (fresh
Pico, wiped flash) boots with actual measured positions immediately
instead of needing apply_sweep_to_config.py's whole serial-write pass
re-run after every fresh flash. Solved LEDs get real cylindrical
coordinates (same coarse pylon->tree shift as apply_sweep_to_config.py,
same underlying triangulation data); every other LED gets the same
out-of-bounds null sentinel (z=-32768) used at runtime, so it's excluded
from any sane volume bound either way.

This only generates the header - it doesn't rebuild/reflash by itself, and
firmware/include/neo_tree_config.hpp's get_default_tree_pos_config_data()
has to actually read from the generated array for this to take effect.

Not final cross-pylon/cross-sweep alignment - see
pylon_geometry.pylon_to_coarse_tree_frame. Regenerate this header (and
rebuild/reflash) whenever sweep data improves.

Usage (venv active, run from mapping/):
    python3 generate_pos_config_header.py --sweep-id 1 --pylon-id A \\
        --standoff-mm 2220 --ground-offset-mm 880 \\
        --output generated_pos_config.hpp
"""
import argparse
import math
import time

import pylon_geometry as geom
import sweep_db

NULL_Z_MM = -32768

HEADER_TEMPLATE = """#pragma once
// AUTO-GENERATED by mapping/generate_pos_config_header.py - do not hand-edit.
// Source: {db} sweep {sweep_id} pylon {pylon_id}, coarse pylon->tree shift
// standoff={standoff}mm ground_offset={ground_offset}mm (see
// pylon_geometry.pylon_to_coarse_tree_frame - a rough placeholder, not
// final cross-pylon alignment). Generated {timestamp}.
// {solved_count} of {count} LEDs solved; the rest are the null sentinel
// (z=-32768) so they land outside any sane volume bound.
//
// Regenerate by re-running that script against updated sweep data, then
// rebuild/reflash.
#include "dcm_physics_math.hpp"
#include <array>

constexpr std::array<cylindrical_coordinates, {count}> generated_led_coordinates = {{{{
{entries}
}}}};
"""


def cartesian_to_cylindrical_deg(x, y, z):
    """
    Mirrors the firmware's transform_cartesian_to_cylindrical exactly
    (post the omega undefined-behavior fix): radius/omega truncated
    toward zero via int(), omega normalized into [0, 360) before
    truncation. See firmware/src/dcm_physics_math.cpp - keep this in sync
    with that function if it changes.
    """
    radius = int(math.sqrt(x * x + y * y))
    omega_rad = math.atan2(y, x)
    if omega_rad < 0:
        omega_rad += 2.0 * math.pi
    omega = int(omega_rad * 180.0 / math.pi)
    return int(z), radius, omega


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--db', default=sweep_db.DEFAULT_DB_PATH)
    parser.add_argument('--sweep-id', default='latest', help="sweep_id to use, or 'latest'")
    parser.add_argument('--pylon-id', default='A')
    parser.add_argument('--count', type=int, default=1000, help="total LED range, 0..count-1")
    parser.add_argument('--standoff-mm', type=float, default=0.0)
    parser.add_argument('--ground-offset-mm', type=float, default=0.0)
    parser.add_argument('--output', default='generated_pos_config.hpp')
    args = parser.parse_args()

    conn = sweep_db.connect(args.db)
    if args.sweep_id == 'latest':
        sweep_id = conn.execute("SELECT MAX(sweep_id) FROM sweeps").fetchone()[0]
    else:
        sweep_id = int(args.sweep_id)

    solves = {}
    for led_position, x, y, z in conn.execute(
            "SELECT led_position, x_mm, y_mm, z_mm FROM session_solves "
            "WHERE sweep_id = ? AND pylon_id = ?", (sweep_id, args.pylon_id)):
        solves[led_position] = (x, y, z)
    conn.close()

    lines = []
    for led in range(args.count):
        if led in solves:
            tx, ty, tz = geom.pylon_to_coarse_tree_frame(
                solves[led], args.standoff_mm, args.ground_offset_mm)
            z, radius, omega = cartesian_to_cylindrical_deg(tx, ty, tz)
        else:
            z, radius, omega = NULL_Z_MM, 0, 0
        lines.append(f"    {{{z}, {radius}, {omega}}},  // led {led}")

    header = HEADER_TEMPLATE.format(
        db=args.db, sweep_id=sweep_id, pylon_id=args.pylon_id,
        standoff=args.standoff_mm, ground_offset=args.ground_offset_mm,
        timestamp=time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime()),
        solved_count=len(solves), count=args.count,
        entries='\n'.join(lines))

    with open(args.output, 'w') as f:
        f.write(header)
    print(f"Wrote {args.output}: {len(solves)}/{args.count} LEDs solved "
          f"(sweep {sweep_id}, pylon {args.pylon_id})")


if __name__ == "__main__":
    main()
