"""
Generates firmware/include/generated_pos_config.hpp: real triangulated LED
positions baked in as compile-time constants, so a clean flash (fresh
Pico, wiped flash) boots with actual measured positions immediately
instead of needing apply_sweep_to_config.py's whole serial-write pass
re-run after every fresh flash. Solved LEDs get real cylindrical
coordinates (same coarse pylon->tree shift as apply_sweep_to_config.py,
same underlying triangulation data); every other LED gets the same
out-of-bounds null sentinel used at runtime (pylon_geometry.NULL_Z_MM/
NULL_RADIUS_MM/NULL_OMEGA_DEG - out of bounds on every axis, not just z;
radius=0 alone collapses to cartesian x=y=0, which real data straddles
on every X/Y/omega sweep - confirmed live as unmapped LEDs blipping on
every frame of an X or Y sweep crossing the origin), so it's excluded
from any sane volume bound on any axis.

This only generates the header - it doesn't rebuild/reflash by itself, and
firmware/include/neo_tree_config.hpp's get_default_tree_pos_config_data()
has to actually read from the generated array for this to take effect.

Two sources: --source sweep (default) pulls one (sweep_id, pylon_id)'s
session_solves and applies the coarse pylon_to_coarse_tree_frame shift -
the original single-session placeholder. --source global pulls from
global_estimates instead, the confidence-weighted merge of every aligned
session (see align_sweep.py) - already in the shared frame established
at bootstrap, no per-call shift needed, and this is the one that actually
benefits from multiple sweeps/pylons' coverage.

Regenerate this header (and rebuild/reflash) whenever sweep data
improves.

Usage (venv active, run from mapping/):
    python3 generate_pos_config_header.py --source global --output generated_pos_config.hpp
    python3 generate_pos_config_header.py --source sweep --sweep-id 1 --pylon-id A \\
        --standoff-mm 2220 --ground-offset-mm 880 --output generated_pos_config.hpp
"""
import argparse
import math
import time

import pylon_geometry as geom
import sweep_db

SWEEP_HEADER_TEMPLATE = """#pragma once
// AUTO-GENERATED by mapping/generate_pos_config_header.py - do not hand-edit.
// Source: {db} sweep {sweep_id} pylon {pylon_id}, coarse pylon->tree shift
// standoff={standoff}mm ground_offset={ground_offset}mm (see
// pylon_geometry.pylon_to_coarse_tree_frame - a rough placeholder, not
// final cross-pylon alignment). Generated {timestamp}.
// {solved_count} of {count} LEDs solved; the rest are pylon_geometry's
// null sentinel (see there) so they land outside any sane volume bound
// on every axis (z, radius, omega, and the x/y it derives to) at once.
//
// Regenerate by re-running that script against updated sweep data, then
// rebuild/reflash.
#include "dcm_physics_math.hpp"
#include <array>

constexpr std::array<cylindrical_coordinates, {count}> generated_led_coordinates = {{{{
{entries}
}}}};
"""

GLOBAL_HEADER_TEMPLATE = """#pragma once
// AUTO-GENERATED by mapping/generate_pos_config_header.py - do not hand-edit.
// Source: {db} global_estimates (confidence-weighted merge of every
// aligned sweep/pylon session - see align_sweep.py). Generated {timestamp}.
// {solved_count} of {count} LEDs covered; the rest are pylon_geometry's
// null sentinel (see there) so they land outside any sane volume bound
// on every axis (z, radius, omega, and the x/y it derives to) at once.
//
// Regenerate by re-running that script after new sweeps are captured and
// aligned, then rebuild/reflash.
#include "dcm_physics_math.hpp"
#include <array>

constexpr std::array<cylindrical_coordinates, {count}> generated_led_coordinates = {{{{
{entries}
}}}};
"""


def cartesian_to_cylindrical_deg(x, y, z):
    """
    Mirrors the firmware's transform_cartesian_to_cylindrical exactly
    (post the omega undefined-behavior fix): radius/omega truncated
    toward zero via int(), omega normalized into [0, 360) before
    truncation. See firmware/src/dcm_physics_math.cpp - keep this in sync
    with that function if it changes.
    """
    radius = int(math.sqrt(x * x + y * y))
    omega_rad = math.atan2(y, x)
    if omega_rad < 0:
        omega_rad += 2.0 * math.pi
    omega = int(omega_rad * 180.0 / math.pi)
    return int(z), radius, omega


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--db', default=sweep_db.DEFAULT_DB_PATH)
    parser.add_argument('--source', choices=['sweep', 'global'], default='sweep')
    parser.add_argument('--sweep-id', default='latest', help="sweep_id to use, or 'latest' (--source sweep only)")
    parser.add_argument('--pylon-id', default='A', help="(--source sweep only)")
    parser.add_argument('--count', type=int, default=1000, help="total LED range, 0..count-1")
    parser.add_argument('--standoff-mm', type=float, default=0.0, help="(--source sweep only)")
    parser.add_argument('--ground-offset-mm', type=float, default=0.0, help="(--source sweep only)")
    parser.add_argument('--max-residual-mm', type=float, default=None,
                         help="(--source sweep only) drop solves with ray_residual_mm above this "
                              "(treated as unsolved / null sentinel) instead of trusting a noisy "
                              "point. Sweep 2 showed a clean natural break around ~20mm - the bulk "
                              "of points sit under 17mm, then a distinct outlier tail jumps to 22mm+.")
    parser.add_argument('--max-cov-trace', type=float, default=1000.0,
                         help="(--source global only) drop global_estimates with cov_xx+cov_yy+cov_zz "
                              "above this instead of trusting a noisy merged point - a single Kabsch-"
                              "fit outlier can land far outside the tree with a covariance orders of "
                              "magnitude above every other point (seen: one point at 311128 vs. a "
                              "normal range of 60-160). Pass 0 to disable.")
    parser.add_argument('--output', default='generated_pos_config.hpp')
    args = parser.parse_args()

    conn = sweep_db.connect(args.db)

    if args.source == 'global':
        solves = {}
        dropped = 0
        for led_position, x, y, z, cxx, cyy, czz in conn.execute(
                "SELECT led_position, x_mm, y_mm, z_mm, cov_xx, cov_yy, cov_zz FROM global_estimates"):
            if args.max_cov_trace and (cxx + cyy + czz) > args.max_cov_trace:
                dropped += 1
                continue
            solves[led_position] = (x, y, z)
        conn.close()
        if args.max_cov_trace:
            print(f"Dropped {dropped} global_estimates with cov_trace > {args.max_cov_trace}")

        lines = []
        for led in range(args.count):
            if led in solves:
                x, y, z = solves[led]
                z_out, radius, omega = cartesian_to_cylindrical_deg(x, y, z)
            else:
                z_out, radius, omega = geom.NULL_Z_MM, geom.NULL_RADIUS_MM, geom.NULL_OMEGA_DEG
            lines.append(f"    {{{z_out}, {radius}, {omega}}},  // led {led}")

        header = GLOBAL_HEADER_TEMPLATE.format(
            db=args.db, timestamp=time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime()),
            solved_count=len(solves), count=args.count, entries='\n'.join(lines))

        with open(args.output, 'w') as f:
            f.write(header)
        print(f"Wrote {args.output}: {len(solves)}/{args.count} LEDs covered (source: global_estimates)")
        return

    if args.sweep_id == 'latest':
        sweep_id = conn.execute("SELECT MAX(sweep_id) FROM sweeps").fetchone()[0]
    else:
        sweep_id = int(args.sweep_id)

    solves = {}
    dropped = 0
    for led_position, x, y, z, resid in conn.execute(
            "SELECT led_position, x_mm, y_mm, z_mm, ray_residual_mm FROM session_solves "
            "WHERE sweep_id = ? AND pylon_id = ?", (sweep_id, args.pylon_id)):
        if args.max_residual_mm is not None and resid > args.max_residual_mm:
            dropped += 1
            continue
        solves[led_position] = (x, y, z)
    conn.close()
    if args.max_residual_mm is not None:
        print(f"Dropped {dropped} solves with ray_residual_mm > {args.max_residual_mm}")

    lines = []
    for led in range(args.count):
        if led in solves:
            tx, ty, tz = geom.pylon_to_coarse_tree_frame(
                solves[led], args.standoff_mm, args.ground_offset_mm)
            z, radius, omega = cartesian_to_cylindrical_deg(tx, ty, tz)
        else:
            z, radius, omega = geom.NULL_Z_MM, geom.NULL_RADIUS_MM, geom.NULL_OMEGA_DEG
        lines.append(f"    {{{z}, {radius}, {omega}}},  // led {led}")

    header = SWEEP_HEADER_TEMPLATE.format(
        db=args.db, sweep_id=sweep_id, pylon_id=args.pylon_id,
        standoff=args.standoff_mm, ground_offset=args.ground_offset_mm,
        timestamp=time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime()),
        solved_count=len(solves), count=args.count,
        entries='\n'.join(lines))

    with open(args.output, 'w') as f:
        f.write(header)
    print(f"Wrote {args.output}: {len(solves)}/{args.count} LEDs solved "
          f"(sweep {sweep_id}, pylon {args.pylon_id})")


if __name__ == "__main__":
    main()
