"""
Write the LED position file the host simulator loads (sim/data/tree_positions.csv).

Real positions come from the same map the firmware is built with
(firmware/include/generated_pos_config.hpp). Until the tree is remapped most
LEDs are unmapped there, so each unmapped LED gets a synthetic stand-in
position drawn to match the measured ones: a height near a randomly chosen
mapped LED's, a radius within +-15% of that LED's, and a uniformly random
angle. That gives the simulator a full, tree-shaped point cloud to develop
against (docs/RENDERER.md section 11.3). Output is deterministic for a given
seed.

Usage:
    python mapping/generate_sim_positions.py [--seed N] [--out PATH]
"""

import argparse
import csv
import random
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HEADER = REPO / "firmware" / "include" / "generated_pos_config.hpp"
DEFAULT_OUT = REPO / "sim" / "data" / "tree_positions.csv"

# pylon_geometry.py's "unmapped" sentinel (z, radius, omega).
NULL_Z_MM = -32768

HEIGHT_JITTER_MM = 60.0
RADIUS_JITTER = 0.15


def load_header_positions():
    text = HEADER.read_text(encoding="utf-8")
    rows = [tuple(int(v) for v in m) for m in re.findall(r"\{(-?\d+), (\d+), (\d+)\},\s*// led (\d+)", text)]
    positions = {}
    for z, radius, omega, index in rows:
        positions[index] = None if z == NULL_Z_MM else (z, radius, omega % 360)
    return positions


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    positions = load_header_positions()
    count = max(positions) + 1
    mapped = [p for p in positions.values() if p is not None]
    if not mapped:
        raise SystemExit("no mapped LEDs in the header - nothing to base synthetic positions on")
    z_lo = min(p[0] for p in mapped)
    z_hi = max(p[0] for p in mapped)

    rng = random.Random(args.seed)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", newline="", encoding="utf-8") as f:
        f.write(f"# Generated by mapping/generate_sim_positions.py --seed {args.seed} from {HEADER.name}.\n")
        f.write(f"# {len(mapped)} mapped, {count - len(mapped)} synthetic. Angles in degrees CCW from +x.\n")
        w = csv.writer(f)
        w.writerow(["index", "z_mm", "radius_mm", "angle_deg", "source"])
        for i in range(count):
            p = positions.get(i)
            if p is not None:
                w.writerow([i, p[0], p[1], p[2], "mapped"])
                continue
            donor = rng.choice(mapped)
            z = min(max(donor[0] + rng.gauss(0.0, HEIGHT_JITTER_MM), z_lo), z_hi)
            radius = donor[1] * rng.uniform(1.0 - RADIUS_JITTER, 1.0 + RADIUS_JITTER)
            angle = rng.uniform(0.0, 360.0)
            w.writerow([i, round(z, 1), round(radius, 1), round(angle, 2), "synthetic"])

    print(f"wrote {args.out.relative_to(REPO)}: {count} LEDs, {len(mapped)} mapped, {count - len(mapped)} synthetic")


if __name__ == "__main__":
    main()
